# ---------------------------------------------------------------------------
# NullFix.py
# Created on: 2012-09-24 14:20:27.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: NullFix <SA_STEWARD_TNC_LANDS> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
SA_STEWARD_TNC_LANDS = arcpy.GetParameterAsText(0)
if SA_STEWARD_TNC_LANDS == '#' or not SA_STEWARD_TNC_LANDS:
    SA_STEWARD_TNC_LANDS = "SA_STEWARD.TNC_LANDS" # provide a default value if unspecified

# Local variables:
v2__26_ = SA_STEWARD_TNC_LANDS
v3__26_ = v2__26_
v2__28_ = SA_STEWARD_TNC_LANDS
v3__28_ = v2__28_
v2__29_ = SA_STEWARD_TNC_LANDS
v3__29_ = v2__29_
v2__31_ = SA_STEWARD_TNC_LANDS
v3__31_ = v2__31_
v2__33_ = SA_STEWARD_TNC_LANDS
v3__33_ = v2__33_
v2__34_ = SA_STEWARD_TNC_LANDS
v3__34_ = v2__34_
v2__2_ = SA_STEWARD_TNC_LANDS
v3__2_ = v2__2_
v2__3_ = SA_STEWARD_TNC_LANDS
v3__3_ = v2__3_
v2__4_ = SA_STEWARD_TNC_LANDS
v3__4_ = v2__4_
v2__5_ = SA_STEWARD_TNC_LANDS
v3__5_ = v2__5_
v2__6_ = SA_STEWARD_TNC_LANDS
v3__6_ = v2__6_
v2__7_ = SA_STEWARD_TNC_LANDS
v3__7_ = v2__7_
v2__8_ = SA_STEWARD_TNC_LANDS
v3__8_ = v2__8_
v2__9_ = SA_STEWARD_TNC_LANDS
v3__9_ = v2__9_
v2__10_ = SA_STEWARD_TNC_LANDS
v3__10_ = v2__10_
v2__11_ = SA_STEWARD_TNC_LANDS
v3__11_ = v2__11_
v2__12_ = SA_STEWARD_TNC_LANDS
v3__12_ = v2__12_
v2__13_ = SA_STEWARD_TNC_LANDS
v3__13_ = v2__13_
v2__14_ = SA_STEWARD_TNC_LANDS
v3__14_ = v2__14_
v2__15_ = SA_STEWARD_TNC_LANDS
v3__15_ = v2__15_
v2__16_ = SA_STEWARD_TNC_LANDS
v3__16_ = v2__16_
v2__17_ = SA_STEWARD_TNC_LANDS
v3__17_ = v2__17_
v2__18_ = SA_STEWARD_TNC_LANDS
v3__18_ = v2__18_
v2__19_ = SA_STEWARD_TNC_LANDS
v3__19_ = v2__19_
v2__20_ = SA_STEWARD_TNC_LANDS
v3__20_ = v2__20_
v2__21_ = SA_STEWARD_TNC_LANDS
v3__21_ = v2__21_
v2__22_ = SA_STEWARD_TNC_LANDS
v3__22_ = v2__22_
v2__23_ = SA_STEWARD_TNC_LANDS
v3__23_ = v2__23_
v2__24_ = SA_STEWARD_TNC_LANDS
v3__24_ = v2__24_
v2__25_ = SA_STEWARD_TNC_LANDS
v3__25_ = v2__25_
v2__27_ = SA_STEWARD_TNC_LANDS
v3__27_ = v2__27_
v2__35_ = SA_STEWARD_TNC_LANDS
v3__35_ = v2__35_
v2__36_ = SA_STEWARD_TNC_LANDS
v3__36_ = v2__36_
v2__37_ = SA_STEWARD_TNC_LANDS
v3__37_ = v2__37_
v2__38_ = SA_STEWARD_TNC_LANDS
v3__38_ = v2__38_
v2__39_ = SA_STEWARD_TNC_LANDS
v3__39_ = v2__39_
v2__40_ = SA_STEWARD_TNC_LANDS
v3__40_ = v2__40_
v2__41_ = SA_STEWARD_TNC_LANDS
v3__41_ = v2__41_

# Process: MA_IFMS_ID (4)
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "\"MA_IFMS_ID\" = 0")

# Process: MA_IFMS_ID CALC (4)
arcpy.CalculateField_management(v2__26_, "MA_IFMS_ID", "NULL", "VB", "")

# Process: AREANAME (4)
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "\"AREANAM\" = '' OR \"AREANAM\" = '<Null>' OR \"AREANAM\" = 'Null' OR \"AREANAM\" = 'NULL' OR \"AREANAM\" = 'null' OR \"AREANAM\" = ' '")

# Process: AREANAME CALC (4)
arcpy.CalculateField_management(v2__28_, "AREANAM", "NULL", "VB", "")

# Process: MABR_NAME (4)
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "\"MABR_NAME\" = '' OR \"MABR_NAME\" = '<Null>' OR \"MABR_NAME\" = ' '")

# Process: MABR_NAME CALC (4)
arcpy.CalculateField_management(v2__29_, "MABR_NAME", "NULL", "VB", "")

# Process: CLS_ACRES (4)
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "\"CLS_ACRES\" = 0")

# Process: CLS_ACRES CALC (4)
arcpy.CalculateField_management(v2__31_, "CLS_ACRES", "NULL", "VB", "")

# Process: TR_IFMS_ID (3)
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "\"TR_IFMS_ID\" = 0")

# Process: TR_IFMS_ID CALC (3)
arcpy.CalculateField_management(v2__33_, "TR_IFMS_ID", "NULL", "VB", "")

# Process: Tract_name (2)
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "\"TRACT_NAME\" = '' OR \"TRACT_NAME\" = '<Null>' OR \"TRACT_NAME\" = ' '")

# Process: TRACT_NAME Calc (2)
arcpy.CalculateField_management(v2__34_, "TRACT_NAME", "NULL", "VB", "")

# Process: state
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "STATE = '' OR STATE = '<Null>' OR STATE = ' '")

# Process: state calc
arcpy.CalculateField_management(v2__2_, "STATE", "NULL", "VB", "")

# Process: source
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "SOURCE = '' OR SOURCE = '<Null>' OR SOURCE = ' '")

# Process: source calc
arcpy.CalculateField_management(v2__3_, "SOURCE", "NULL", "VB", "")

# Process: areaname2
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "AREANAM2 = '' OR AREANAM2 = '<Null>' OR AREANAM2 = ' '")

# Process: areaname2 calc
arcpy.CalculateField_management(v2__4_, "AREANAM2", "NULL", "VB", "")

# Process: designation
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "DESGNTN = '' OR DESGNTN = '<Null>' OR DESGNTN = ' '")

# Process: designation calc
arcpy.CalculateField_management(v2__5_, "DESGNTN", "NULL", "VB", "")

# Process: designation 2
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "DESGNTN2 = '' OR DESGNTN2 = '<Null>' OR DESGNTN2 = ' '")

# Process: designation 2 calc 
arcpy.CalculateField_management(v2__6_, "DESGNTN2", "NULL", "VB", "")

# Process: owner
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "OWNER = '' OR OWNER = '<Null>' OR OWNER = ' '")

# Process: owner calc
arcpy.CalculateField_management(v2__7_, "OWNER", "NULL", "VB", "")

# Process: agency
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "AGENCY = '' OR AGENCY = '<Null>' OR AGENCY = ' '")

# Process: agency calc
arcpy.CalculateField_management(v2__8_, "AGENCY", "NULL", "VB", "")

# Process: constat
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "CONSTAT = '' OR CONSTAT = '<Null>' OR CONSTAT = ' '")

# Process: constat calc
arcpy.CalculateField_management(v2__9_, "CONSTAT", "NULL", "VB", "")

# Process: tenureexp
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "TENUREEXP = '' OR TENUREEXP = ' ' OR TENUREEXP = '<Null>' OR TENUREEXP < TO_DATE('1951-1-1 00:00:00','YYYY-MM-DD HH24:MI:SS')")

# Process: tenureexp calc
arcpy.CalculateField_management(v2__10_, "TENUREEXP", "NULL", "VB", "")

# Process: icuncat
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "IUCNCAT = '' OR IUCNCAT = '<Null>' OR IUCNCAT = ' '")

# Process: icuncat calc
arcpy.CalculateField_management(v2__11_, "IUCNCAT", "NULL", "VB", "")

# Process: gapcat
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "GAPCAT = '' OR GAPCAT = '<Null>' OR GAPCAT = ' ' OR GAPCAT = '0'")

# Process: gapcat calc
arcpy.CalculateField_management(v2__12_, "GAPCAT", "NULL", "VB", "")

# Process: prothold
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "PROTHOLD = '' OR PROTHOLD = '<Null>' OR PROTHOLD = ' '")

# Process: prothold calc
arcpy.CalculateField_management(v2__13_, "PROTHOLD", "NULL", "VB", "")

# Process: protmech
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "PROTMECH = '' OR PROTMECH = '<Null>' OR PROTMECH = ' '")

# Process: protmech calc
arcpy.CalculateField_management(v2__14_, "PROTMECH", "NULL", "VB", "")

# Process: protmech 2
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "PROTMECH2 = '' OR PROTMECH2 = '<Null>' OR PROTMECH2 = ' '")

# Process: protmech 2 calc
arcpy.CalculateField_management(v2__15_, "PROTMECH2", "NULL", "VB", "")

# Process: protprog
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "PROTPROG = '' OR PROTPROG = '<Null>' OR PROTPROG = ' '")

# Process: protprog calc
arcpy.CalculateField_management(v2__16_, "PROTPROG", "NULL", "VB", "")

# Process: protdate
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "PROTDATE< TO_DATE('1951-1-1 00:00:00','YYYY-MM-DD HH24:MI:SS')")

# Process: protdate calc
arcpy.CalculateField_management(v2__17_, "PROTDATE", "NULL", "VB", "")

# Process: prodatpr
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "PRODATPR = '' OR PRODATPR = '<Null>' OR PRODATPR = ' '")

# Process: prodatpr calc
arcpy.CalculateField_management(v2__18_, "PRODATPR", "NULL", "VB", "")

# Process: confidence
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "CF = '' OR CF = '<Null>' OR CF = ' '")

# Process: confidence calc
arcpy.CalculateField_management(v2__19_, "CF", "NULL", "VB", "")

# Process: country
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "COUNTRY = '' OR COUNTRY = '<Null>' OR COUNTRY = ' '")

# Process: country calc
arcpy.CalculateField_management(v2__20_, "COUNTRY", "NULL", "VB", "")

# Process: moddate
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "MOD_DATE < TO_DATE('1951-1-1 00:00:00','YYYY-MM-DD HH24:MI:SS')")

# Process: moddate calc
arcpy.CalculateField_management(v2__21_, "MOD_DATE", "NULL", "VB", "")

# Process: clstransdate
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "CLSTRANSDA < TO_DATE('1951-1-1 00:00:00','YYYY-MM-DD HH24:MI:SS')")

# Process: clstransdate calc
arcpy.CalculateField_management(v2__22_, "CLSTRANSDA", "NULL", "VB", "")

# Process: source id
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "SOURCE_ID = '' OR SOURCE_ID = '<Null>' OR SOURCE_ID = ' '")

# Process: source id calc
arcpy.CalculateField_management(v2__23_, "SOURCE_ID", "NULL", "VB", "")

# Process: interest holder
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "INT_HOLD = '' OR INT_HOLD = '<Null>' OR INT_HOLD = ' '")

# Process: interest holder calc
arcpy.CalculateField_management(v2__24_, "INT_HOLD", "NULL", "VB", "")

# Process: dsgntn_l
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "DSGNTN_L = '' OR DSGNTN_L = '<Null>' OR DSGNTN_L = ' '")

# Process: dsgntn_l calc
arcpy.CalculateField_management(v2__25_, "DSGNTN_L", "NULL", "VB", "")

# Process: dsgntn_L2
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "DSGNTN_L2 = '' OR DSGNTN_L2 = '<Null>' OR DSGNTN_L2 = ' '")

# Process: dsgntn_L2 calc 
arcpy.CalculateField_management(v2__27_, "DSGNTN_L2", "NULL", "VB", "")

# Process: status
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "STATUS = '' OR STATUS = '<Null>' OR STATUS = ' '")

# Process: status calc
arcpy.CalculateField_management(v2__35_, "STATUS", "NULL", "VB", "")

# Process: legal record
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "LEGAL_REC = '' OR LEGAL_REC = '<Null>' OR LEGAL_REC = ' '")

# Process: legal record calc
arcpy.CalculateField_management(v2__36_, "LEGAL_REC", "NULL", "VB", "")

# Process: sensdata
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "SENSDATA = '' OR SENSDATA = '<Null>' OR SENSDATA = ' '")

# Process: sensdata calc
arcpy.CalculateField_management(v2__37_, "SENSDATA", "NULL", "VB", "")

# Process: intent
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "CMS_INTENT = '' OR CMS_INTENT = '<Null>' OR CMS_INTENT = ' '")

# Process: intent calc
arcpy.CalculateField_management(v2__38_, "CMS_INTENT", "NULL", "VB", "")

# Process: Duration
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "CMS_DURATN = '' OR CMS_DURATN = '<Null>' OR CMS_DURATN = ' '")

# Process: duration calc
arcpy.CalculateField_management(v2__39_, "CMS_DURATN", "NULL", "VB", "")

# Process: EMP
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "CMS_EMP = '' OR CMS_EMP = '<Null>' OR CMS_EMP = ' '")

# Process: EMP calc
arcpy.CalculateField_management(v2__40_, "CMS_EMP", "NULL", "VB", "")

# Process: qc exception
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "QC_EXCEPT = '' OR QC_EXCEPT = '<Null>' OR QC_EXCEPT = ' '")

# Process: qc exception calc
arcpy.CalculateField_management(v2__41_, "QC_EXCEPT", "NULL", "VB", "")

