# ---------------------------------------------------------------------------
# Attribute_Update.py
# Created on: 2012-09-24 14:24:20.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Attribute_Update <SA_STEWARD_TNC_LANDS> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
SA_STEWARD_TNC_LANDS = arcpy.GetParameterAsText(0)
if SA_STEWARD_TNC_LANDS == '#' or not SA_STEWARD_TNC_LANDS:
    SA_STEWARD_TNC_LANDS = "SA_STEWARD.TNC_LANDS" # provide a default value if unspecified

# Local variables:
v2__5_ = SA_STEWARD_TNC_LANDS
v3__5_ = v2__5_
v2__7_ = SA_STEWARD_TNC_LANDS
v3__7_ = v2__7_
v2__12_ = SA_STEWARD_TNC_LANDS
v3__12_ = v2__12_
v2__13_ = SA_STEWARD_TNC_LANDS
v3__13_ = v2__13_
v2__38_ = SA_STEWARD_TNC_LANDS
v3__38_ = v2__38_
v2__39_ = SA_STEWARD_TNC_LANDS
v3__39_ = v2__39_
v2__40_ = SA_STEWARD_TNC_LANDS
v3__40_ = v2__40_
v2__2_ = SA_STEWARD_TNC_LANDS
v3__2_ = v2__2_
v2__3_ = SA_STEWARD_TNC_LANDS
v3__3_ = v2__3_
v2__4_ = SA_STEWARD_TNC_LANDS
v3__4_ = v2__4_
v2__6_ = SA_STEWARD_TNC_LANDS
v3__6_ = v2__6_

# Process: desgntn is NULL
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "DESGNTN Is NULL")

# Process: set designation = "Conservation Preserve"
arcpy.CalculateField_management(v2__5_, "DESGNTN", "\"Conservation Preserve\"", "VB", "")

# Process: owner is NULL
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "OWNER Is NULL")

# Process: set owner = "Private"
arcpy.CalculateField_management(v2__7_, "OWNER", "\"Private\"", "VB", "")

# Process: select fee-simple / agreement (gap)
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "(PROTMECH = 'Fee-simple ownership' OR PROTMECH = 'Fee-simple / easement combination' OR PROTMECH = 'Agreement') AND GAPCAT IS NULL")

# Process: set gapcat = 1
arcpy.CalculateField_management(v2__12_, "GAPCAT", "\"1\"", "VB", "")

# Process: prothold is NULL
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "PROTHOLD Is NULL")

# Process: set prothold = "The Nature Conservancy"
arcpy.CalculateField_management(v2__13_, "PROTHOLD", "\"The Nature Conservancy\"", "VB", "")

# Process: select fee-simple / agreement (intent)
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "(PROTMECH = 'Fee-simple ownership' OR PROTMECH = 'Fee-simple / easement combination' OR PROTMECH = 'Agreement') AND CMS_INTENT IS NULL")

# Process: set cms_intent = "Biodiversity Focus"
arcpy.CalculateField_management(v2__38_, "CMS_INTENT", "\"Biodiversity Focus\"", "VB", "")

# Process: select easement / fee-simple (duratn)
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "(PROTMECH= 'Full conservation easement' OR PROTMECH = 'Fee-simple ownership' OR PROTMECH = 'Fee-simple / easement combination') AND CMS_DURATN IS NULL")

# Process: set cms_duratn = "Permanent Commitment"
arcpy.CalculateField_management(v2__39_, "CMS_DURATN", "\"Permanent Commitment\"", "VB", "")

# Process: select easement / fee-simple (emp)
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "(PROTMECH= 'Full conservation easement' OR PROTMECH = 'Fee-simple ownership' OR PROTMECH = 'Fee-simple / easement combination') AND CMS_EMP IS NULL")

# Process: set cms_emp = "High Potential"
arcpy.CalculateField_management(v2__40_, "CMS_EMP", "\"High Potential\"", "VB", "")

# Process: select deed restriction / easement (intent)
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "(PROTMECH = 'Deed Restriction' OR PROTMECH= 'Full conservation easement') AND CMS_INTENT IS NULL")

# Process: set cms_intent = "Biodiversity Compatible"
arcpy.CalculateField_management(v2__2_, "CMS_INTENT", "\"Biodiversity Compatible\"", "VB", "")

# Process: select deed restriction (duratn)
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "PROTMECH = 'Deed Restriction' AND CMS_ DURATN IS NULL")

# Process: set cms_duratn = "Long Term Commitment"
arcpy.CalculateField_management(v2__3_, "CMS_DURATN", "\"Long Term Commitment\"", "VB", "")

# Process: select deed restriction (emp)
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "PROTMECH = 'Deed Restriction' AND CMS_ EMP IS NULL")

# Process: set cms_emp = "Moderate Potential"
arcpy.CalculateField_management(v2__4_, "CMS_EMP", "\"Moderate Potential\"", "VB", "")

# Process: select deed restriction / easement (gap)
arcpy.SelectLayerByAttribute_management(SA_STEWARD_TNC_LANDS, "NEW_SELECTION", "(PROTMECH = 'Deed Restriction' OR PROTMECH= 'Full conservation easement') AND GAPCAT IS NULL")

# Process: set gapcat = 2
arcpy.CalculateField_management(v2__6_, "GAPCAT", "\"2\"", "VB", "")

