# ---------------------------------------------------------------------------
# cema1to1.py
# Created on: 2012-09-24 14:24:50.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: cema1to1 <SA_STEWARD_TNC_LANDS> <cema1to1> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
SA_STEWARD_TNC_LANDS = arcpy.GetParameterAsText(0)
if SA_STEWARD_TNC_LANDS == '#' or not SA_STEWARD_TNC_LANDS:
    SA_STEWARD_TNC_LANDS = "SA_STEWARD.TNC_LANDS" # provide a default value if unspecified

cema1to1 = arcpy.GetParameterAsText(1)
if cema1to1 == '#' or not cema1to1:
    cema1to1 = "cema1to1" # provide a default value if unspecified

# Local variables:
v1 = cema1to1
v2 = v1
v3 = v2
v4 = v1
v5 = v4
v6 = v1
v7 = v6
v8 = v1
v9 = v8
v10 = v1
v11 = v10
v12 = v1
v13 = v12
v14 = v1
v15 = v14
v16 = v1
v17 = v16
v18 = v1
v19 = v18
v20 = v1
v21 = v20
v22 = v1
v23 = v22
v24 = v1
v25 = v24
v16__2_ = v1
v17__2_ = v16__2_
v24__2_ = v1
v25__2_ = v24__2_
SA_STEWARD_TNC_LANDS__2_ = v25__2_

# Process: Add Join
arcpy.AddJoin_management(SA_STEWARD_TNC_LANDS, "MA_IFMS_ID", cema1to1, "MA_IFMS_ID", "KEEP_COMMON")

# Process: Select NULL AREANAM
arcpy.SelectLayerByAttribute_management(v1, "NEW_SELECTION", "SA_STEWARD.TNC_LANDS.MA_IFMS_ID IS NOT NULL AND SA_STEWARD.TNC_LANDS.TR_IFMS_ID IS NULL AND SA_STEWARD.TNC_LANDS.AREANAM IS NULL")

# Process: AREANAM
arcpy.CalculateField_management(v2, "SA_STEWARD.TNC_LANDS.AREANAM", "[cema1to1.AREANAM] + \" Easement\"", "VB", "")

# Process: Select NULL DESGNTN
arcpy.SelectLayerByAttribute_management(v1, "NEW_SELECTION", "SA_STEWARD.TNC_LANDS.MA_IFMS_ID IS NOT NULL AND SA_STEWARD.TNC_LANDS.TR_IFMS_ID IS NULL AND SA_STEWARD.TNC_LANDS.DESGNTN IS NULL")

# Process: DESGNTN
arcpy.CalculateField_management(v4, "SA_STEWARD.TNC_LANDS.DESGNTN", "\"Conservation Preserve\"", "VB", "")

# Process: Select NULL OWNER
arcpy.SelectLayerByAttribute_management(v1, "NEW_SELECTION", "SA_STEWARD.TNC_LANDS.MA_IFMS_ID IS NOT NULL AND SA_STEWARD.TNC_LANDS.TR_IFMS_ID IS NULL AND SA_STEWARD.TNC_LANDS.OWNER IS NULL")

# Process: OWNER
arcpy.CalculateField_management(v6, "SA_STEWARD.TNC_LANDS.OWNER", "\"Private\"", "VB", "")

# Process: Select NULL GAPCAT
arcpy.SelectLayerByAttribute_management(v1, "NEW_SELECTION", "SA_STEWARD.TNC_LANDS.MA_IFMS_ID IS NOT NULL AND SA_STEWARD.TNC_LANDS.TR_IFMS_ID IS NULL AND SA_STEWARD.TNC_LANDS.GAPCAT IS NULL")

# Process: GAPCAT
arcpy.CalculateField_management(v8, "SA_STEWARD.TNC_LANDS.GAPCAT", "\"2\"", "VB", "")

# Process: Select NULL PROTHOLD
arcpy.SelectLayerByAttribute_management(v1, "NEW_SELECTION", "SA_STEWARD.TNC_LANDS.MA_IFMS_ID IS NOT NULL AND SA_STEWARD.TNC_LANDS.TR_IFMS_ID IS NULL AND SA_STEWARD.TNC_LANDS.PROTHOLD IS NULL")

# Process: PROTHOLD
arcpy.CalculateField_management(v10, "SA_STEWARD.TNC_LANDS.PROTHOLD", "\"The Nature Conservancy\"", "VB", "")

# Process: Select 0
arcpy.SelectLayerByAttribute_management(v1, "NEW_SELECTION", "SA_STEWARD.TNC_LANDS.MA_IFMS_ID IS NOT NULL AND SA_STEWARD.TNC_LANDS.TR_IFMS_ID IS NULL")

# Process: PROMECH
arcpy.CalculateField_management(v12, "SA_STEWARD.TNC_LANDS.PROTMECH", "\"Full conservation easement\"", "VB", "")

# Process: Select1
arcpy.SelectLayerByAttribute_management(v1, "NEW_SELECTION", "SA_STEWARD.TNC_LANDS.MA_IFMS_ID IS NOT NULL AND SA_STEWARD.TNC_LANDS.TR_IFMS_ID IS NULL")

# Process: CLSTRANSDA
arcpy.CalculateField_management(v14, "SA_STEWARD.TNC_LANDS.CLSTRANSDA", "[cema1to1.CLSTRANSDA]", "VB", "")

# Process: Select
arcpy.SelectLayerByAttribute_management(v1, "NEW_SELECTION", "SA_STEWARD.TNC_LANDS.MA_IFMS_ID IS NOT NULL AND SA_STEWARD.TNC_LANDS.TR_IFMS_ID IS NULL")

# Process: MABR_NAME
arcpy.CalculateField_management(v16, "SA_STEWARD.TNC_LANDS.MABR_NAME", "[cema1to1.MABR_NAME]", "VB", "")

# Process: Select NULL CMS_INTENT
arcpy.SelectLayerByAttribute_management(v1, "NEW_SELECTION", "SA_STEWARD.TNC_LANDS.MA_IFMS_ID IS NOT NULL AND SA_STEWARD.TNC_LANDS.TR_IFMS_ID IS NULL AND SA_STEWARD.TNC_LANDS.CMS_INTENT IS NULL")

# Process: CMS_INTENT
arcpy.CalculateField_management(v18, "SA_STEWARD.TNC_LANDS.CMS_INTENT", "\"Biodiversity Compatible\"", "VB", "")

# Process: Select NULL CMS_DURATN
arcpy.SelectLayerByAttribute_management(v1, "NEW_SELECTION", "SA_STEWARD.TNC_LANDS.MA_IFMS_ID IS NOT NULL AND SA_STEWARD.TNC_LANDS.TR_IFMS_ID IS NULL AND  SA_STEWARD.TNC_LANDS.CMS_DURATN IS NULL")

# Process: CMS_DURATN
arcpy.CalculateField_management(v20, "SA_STEWARD.TNC_LANDS.CMS_DURATN", "\"Permanent Commitment\"", "VB", "")

# Process: Select NULL CMS_EMP
arcpy.SelectLayerByAttribute_management(v1, "NEW_SELECTION", "SA_STEWARD.TNC_LANDS.MA_IFMS_ID IS NOT NULL AND SA_STEWARD.TNC_LANDS.TR_IFMS_ID IS NULL AND SA_STEWARD.TNC_LANDS.CMS_EMP IS NULL")

# Process: CMS_EMP
arcpy.CalculateField_management(v22, "SA_STEWARD.TNC_LANDS.CMS_EMP", "\"High Potential\"", "VB", "")

# Process: Select NULL CLS_ACRES 
arcpy.SelectLayerByAttribute_management(v1, "NEW_SELECTION", "SA_STEWARD.TNC_LANDS.MA_IFMS_ID IS NOT NULL AND SA_STEWARD.TNC_LANDS.TR_IFMS_ID IS NULL")

# Process: CLS_ACRES
arcpy.CalculateField_management(v24, "SA_STEWARD.TNC_LANDS.CLS_ACRES", "[cema1to1.CLS_ACRES]", "VB", "")

# Process: Select 
arcpy.SelectLayerByAttribute_management(v1, "NEW_SELECTION", "SA_STEWARD.TNC_LANDS.MA_IFMS_ID IS NOT NULL AND SA_STEWARD.TNC_LANDS.TR_IFMS_ID IS NULL")

# Process: TRACT_NAME
arcpy.CalculateField_management(v16__2_, "SA_STEWARD.TNC_LANDS.TRACT_NAME", "[cema1to1.TRACT_NAME]", "VB", "")

# Process: Select TR_IFMS_ID
arcpy.SelectLayerByAttribute_management(v1, "NEW_SELECTION", "SA_STEWARD.TNC_LANDS.MA_IFMS_ID IS NOT NULL AND SA_STEWARD.TNC_LANDS.TR_IFMS_ID IS NULL")

# Process: TR_IFMS_ID
arcpy.CalculateField_management(v24__2_, "SA_STEWARD.TNC_LANDS.TR_IFMS_ID", "[cema1to1.TR_IFMS_ID]", "VB", "")

# Process: Remove Join
arcpy.RemoveJoin_management(v25__2_, "cema1to1")

